services:
  mysql:
    container_name: mysql1
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: shopdb
      MYSQL_USER: user
      MYSQL_PASSWORD: userpassword
    ports:
      - "5555:3306"
    networks:
      - app-network
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      timeout: 20s
      retries: 10

  mavenapp:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      DATABASE_URL: jdbc:mysql://mysql1:5555/shopdb?allowPublicKeyRetrieval=true&useSSL=false&createDatabaseIfNotExist=true
      DATABASE_USER: root
      DATABASE_PASSWORD: rootpassword
    ports:
      - "8080:8080"
    networks:
      - app-network
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      MYSQL_ROOT_PASSWORD: rootpassword
    ports:
      - "8081:80"
    depends_on:
      - mysql
    networks:
      - app-network
networks:
  app-network:
    driver: bridge